# Generated by Django 4.1.7 on 2023-03-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dtwee_app", "0002_alter_tweet_like_count_alter_tweet_reply_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tweet",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
